apiVersion: v1
kind: LimitRange
metadata:
  name: mastodon-limit-range
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  limits:
  - max:
      cpu: "{{ div  .Values.resources.cpu  6 }}m"
      memory: "{{ div  .Values.resources.memory  6 }}Mi"
    # defaultRequest:
    #   cpu: "{{ div .Values.resources.cpu 10 }}m"
    #   memory: "{{ div .Values.resources.memory 10 }}Mi"
    type: Container



# the rest is divided equally on these 6 pods
# taiga-async,
# taiga-async-rabbitmq,
# taiga-events,
# taiga-events-rabbitmq,
# taiga-back